//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeProfile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignClienttoEmp
    {
        public int ID { get; set; }
        public int ClientId { get; set; }
        public string ClientName { get; set; }
        public Nullable<int> EID { get; set; }
        public Nullable<System.DateTime> POS { get; set; }
        public Nullable<System.DateTime> POE { get; set; }
        public Nullable<decimal> ClientBilling { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ClientEmail { get; set; }
        public string ClientManagerName { get; set; }
        public string DesignationatClient { get; set; }
    
        public virtual EmployeeDetail EmployeeDetail { get; set; }
    }
}
